services:
  mysql:
    image: mysql:8.0
    container_name: mysql-deporte
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: deporteParaTodos
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/DDL-MYSQL.sql:/docker-entrypoint-initdb.d/DDL-MYSQL.sql
      - mysql_data:/var/lib/mysql
    command: --lower-case-table-names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
