DROP TABLE "NOTIFICACION_ENTRADA" cascade constraints;
DROP TABLE "TBL_ALERTA" cascade constraints;
DROP TABLE "TBL_ALUMNO" cascade constraints; 
DROP TABLE "TBL_ASISTENCIA" cascade constraints;
DROP TABLE "TBL_BANDEJA_ENTRADA" cascade constraints;
DROP TABLE "TBL_BANDEJA_SALIDA" cascade constraints;
DROP TABLE "TBL_CATEGORIA_CURSO" cascade constraints;
DROP TABLE "TBL_CLASE" cascade constraints;
DROP TABLE "TBL_COORDINADOR" cascade constraints;
DROP TABLE "TBL_CURSO" cascade constraints; 
DROP TABLE "TBL_DEPORTE" cascade constraints;
DROP TABLE "TBL_FACULTAD" cascade constraints;
DROP TABLE "TBL_GRUPO" cascade constraints;
DROP TABLE "TBL_HORARIO" cascade constraints;
DROP TABLE "TBL_IMAGEN" cascade constraints;
DROP TABLE "TBL_INSCRIPCION" cascade constraints;
DROP TABLE "TBL_INSTRUCTOR" cascade constraints;
DROP TABLE "TBL_NOTIFICACION" cascade constraints;
DROP TABLE "TBL_PERFIL" cascade constraints;
DROP TABLE "TBL_INTERMEDIA_ALUMNO_PROGRAMA" cascade constraints;
DROP TABLE "TBL_PROGRAMA" cascade constraints;
DROP SEQUENCE SEQ_ID_IMAGEN;
DROP SEQUENCE SEQ_CLS_CODIGO;
DROP SEQUENCE SEQ_ID_HORARIO;
DROP SEQUENCE SEQ_ESC_ID;

--------------------------------------------------------
-- Archivo creado  - sábado-mayo-24-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_CLS_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_CLS_CODIGO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_HORARIO
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ID_HORARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_IMAGEN
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ID_IMAGEN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ESC_ID
--------------------------------------------------------
   CREATE SEQUENCE  "SEQ_ESC_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table NOTIFICACION_ENTRADA
--------------------------------------------------------

--CREATE ESCENARIO
CREATE TABLE TBL_ESCENARIO (
    META_ELIMINADO   NUMBER(1)          DEFAULT 0 NOT NULL,
    ESC_ID           NUMBER(*,0)        NOT NULL,
    ESC_NOMBRE       VARCHAR2(100 BYTE) NOT NULL,
    ESC_DESCRIPCION  VARCHAR2(500 BYTE),
    ESC_NUM_TRIBUNAS NUMBER(3)          DEFAULT 0 NOT NULL,
    ESC_DISPONIBLE   NUMBER(1)          DEFAULT 1 NOT NULL,
    CONSTRAINT PK_TBL_ESCENARIO        PRIMARY KEY (ESC_ID),
    CONSTRAINT UQ_TBL_ESCENARIO_NOMBRE UNIQUE (ESC_NOMBRE)
);
COMMENT ON TABLE  TBL_ESCENARIO IS 'CATALOGO DE ESCENARIOS DEPORTIVOS DE LA UNIVERSIDAD';
COMMENT ON COLUMN TBL_ESCENARIO.META_ELIMINADO   IS '1 SI EL REGISTRO FUE ELIMINADO LOGICAMENTE, 0 DE LO CONTRARIO';
COMMENT ON COLUMN TBL_ESCENARIO.ESC_DISPONIBLE   IS '1 SI EL ESCENARIO ESTA OPERATIVO, 0 SI ESTA FUERA DE SERVICIO TEMPORALMENTE';
COMMENT ON COLUMN TBL_ESCENARIO.ESC_NUM_TRIBUNAS IS 'CANTIDAD DE TRIBUNAS DEL ESCENARIO; 0 SI NO TIENE';

  --create deporte

CREATE TABLE TBL_DEPORTE 
	(	
	META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	DEPT_NOMBRE VARCHAR2(100 BYTE) NOT NULL,
	CONSTRAINT PK_TBL_DEPORTE PRIMARY KEY(DEPT_NOMBRE)
   );
COMMENT ON TABLE TBL_DEPORTE IS 'UN TIPO DE DEPORTE PRACTICADO EN EL PROGRAMA';
COMMENT ON COLUMN TBL_DEPORTE.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

--create imagen
CREATE TABLE TBL_IMAGEN 
   (
	META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	IMG_ID NUMBER(*,0) NOT NULL,
	IMG_NOMBRE VARCHAR2(200 BYTE) NOT NULL, 
	IMG_TIPO_ARCHIVO VARCHAR2(100 BYTE) NOT NULL, 
	IMG_LONGITUD NUMBER(*,0) NOT NULL, 
	IMG_DATOS BLOB NOT NULL,
	CONSTRAINT PK_TBL_IMAGEN PRIMARY KEY (IMG_ID)
   );
COMMENT ON TABLE TBL_IMAGEN IS 'ALMACENA LA LOS METADATOS DE UNA IMAGEN Y SU CONTENIDO EN BINARIO';
COMMENT ON COLUMN TBL_IMAGEN.IMG_TIPO_ARCHIVO IS 'REPRESENTA EL TIPO DE ARCHIVO SEGUN EL ESTANDAR MIME';
COMMENT ON COLUMN TBL_IMAGEN.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';


--CREATE CATEGORIA
CREATE TABLE TBL_CATEGORIA_CURSO 
   (	
	META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	CAT_TITULO VARCHAR2(100 BYTE) NOT NULL, 
	CAT_DESCRIPCION VARCHAR2(1000 BYTE) NOT NULL,
	CAT_IMAGEN NUMBER(*,0),
	CONSTRAINT PK_TBL_CATEGORIA_CURSO PRIMARY KEY(CAT_TITULO),
	CONSTRAINT FK_CATEGORIA_CURSO_IMAGEN FOREIGN KEY(CAT_IMAGEN) REFERENCES TBL_IMAGEN(IMG_ID) ON DELETE SET NULL
   );
COMMENT ON TABLE TBL_CATEGORIA_CURSO IS 'LA CATEGORIA AGRUPA A CURSOS, DE MOMENTO SE TIENE A SELECCIONADO, SEMILLERO Y FORMATIVO';
COMMENT ON COLUMN TBL_CATEGORIA_CURSO.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

   --CREATE PERFIL
 CREATE TABLE TBL_PERFIL
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
   PERF_ID VARCHAR2(50 BYTE) NOT NULL, 
	PERF_NOMBRE VARCHAR2(100 BYTE) NOT NULL, 
	PERF_CORREO VARCHAR2(100 BYTE) NOT NULL, 
	PERF_IMAGEN NUMBER(*,0),
	PERF_TIPOID VARCHAR2(50 BYTE) NOT NULL, 
	PERF_SEXO VARCHAR2(10 BYTE) NOT NULL,
	CONSTRAINT CKC_TBL_PERF_SEXO CHECK (PERF_SEXO IN ('M','F')),
	CONSTRAINT CKC_TBL_PERF_TIPOID CHECK (PERF_TIPOID IN('CC','TI','CE','PP','PEP','DIE')),
	CONSTRAINT FK_PERFIL_IMAGEN FOREIGN KEY(PERF_IMAGEN) REFERENCES TBL_IMAGEN(IMG_ID),
	CONSTRAINT PK_TBL_PERFIL PRIMARY KEY(PERF_ID)
   );
   COMMENT ON COLUMN TBL_PERFIL.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';
   
   
   CREATE TABLE TBL_INSTRUCTOR
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	PERF_ID VARCHAR2(50 BYTE) NOT NULL, 
	CONSTRAINT FK_INSTRUCTOR_PERFIL FOREIGN KEY(PERF_ID) REFERENCES TBL_PERFIL(PERF_ID) ON DELETE SET NULL,
	CONSTRAINT PF_TBL_INSTRUCTOR PRIMARY KEY(PERF_ID) --REVISAR SI ES NECESARIO PONER RESTRICCION AL CODIGO
   );
   COMMENT ON COLUMN TBL_INSTRUCTOR.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

--CREATE CURSO
CREATE TABLE TBL_CURSO
   (
	META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	CUR_NOMBRE VARCHAR2(100 BYTE) NOT NULL, --EL NOMBRE DEL CURSO NO PUEDE SSER UNIQUE POR QUE EN DISTINTAS CATEOGRIA PUEDE HABER EL CURSO CON EL MISMO NOMBRE, POR TANTO LO MEJOR ES GESTIONAR CLAVE COMPUESTA ENTRE NOMBRE GRUPO Y CLAVE CATEGORIA
	DEPT_NOMBRE VARCHAR2(100 BYTE),
	CAT_TITULO VARCHAR2(100 BYTE) NOT NULL,
	CUR_DESCRIPCION VARCHAR2(1000 BYTE) NOT NULL,
	CUR_IMAGEN NUMBER(*,0),
	CUR_HORARIO VARCHAR2(200 BYTE),
	CUR_ESTADO_INSCRIPCIONES VARCHAR2(10) DEFAULT 'ABIERTO',
	CONSTRAINT FK_TBL_CURSO_DEPORTE FOREIGN KEY(DEPT_NOMBRE) REFERENCES TBL_DEPORTE(DEPT_NOMBRE) ON DELETE SET NULL,
	CONSTRAINT FK_TBL_CURSO_IMAGEN FOREIGN KEY(CUR_IMAGEN) REFERENCES TBL_IMAGEN(IMG_ID) ON DELETE SET NULL,
	CONSTRAINT FK_TBL_CURSO_CATEGORIA FOREIGN KEY(CAT_TITULO) REFERENCES TBL_CATEGORIA_CURSO(CAT_TITULO) ON DELETE SET NULL,
	CONSTRAINT PK_TBL_CURSO PRIMARY KEY(CUR_NOMBRE, CAT_TITULO)
   );
COMMENT ON TABLE TBL_CURSO IS 'LOS CURSOS POSEEN LA INFORMACION GENERAL Y ENCAPSULAN EN ELLOS LOS GRUPOS LOS CUALES SON INFORMACION ESPECIFICA';
COMMENT ON COLUMN TBL_CURSO.DEPT_NOMBRE IS 'CAMPO PARA LA CLAVE FORANEA DE DEPORTE, DE ESTE MODO UN CURSO POSEE UN DEPORTE ASIGNADO';
COMMENT ON COLUMN TBL_CURSO.CAT_TITULO IS 'CAMPO PARA LA CLAVE DE CATEGORIA ESTO PERMITIRA AGRUPOR LOS CURSOS EN CATEGORIAS Y TAMBIEN SERA ASIGNADO COMO PARTE DE UNA CLAVE COMPUESTA PARA EL CURSO';
COMMENT ON COLUMN TBL_CURSO.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

CREATE TABLE "TBL_GRUPO"
   (	"META_ELIMINADO" NUMBER(*,0),
	"GRP_ANIO" NUMBER(*,0),
	"GRP_ITERABLE" NUMBER(*,0),
	"CUR_NOMBRE" VARCHAR2(100 BYTE),
	"CAT_TITULO" VARCHAR2(100 BYTE),
	"GRP_IMAGEN" NUMBER(*,0),
	"GRP_CUPOS" NUMBER(*,0),
	"GRP_FECHACREACION" DATE,
	"GRP_FECHA_FINALIZACION" DATE,
	"GRP_FECHA_INSCRIP_APERTURA" DATE,
	"GRP_FECHA_INSCRIP_CIERRE" DATE,
	"GRP_PERIODO" NUMBER(1) DEFAULT 1 NOT NULL,
	"PERF_ID" VARCHAR2(50 BYTE),
    CONSTRAINT FK_GRUPO_IMAGEN FOREIGN KEY(GRP_IMAGEN) REFERENCES TBL_IMAGEN(IMG_ID) ON DELETE SET NULL,
	CONSTRAINT FK_GRUPO_CURSO FOREIGN KEY(CUR_NOMBRE, CAT_TITULO) REFERENCES TBL_CURSO(CUR_NOMBRE, CAT_TITULO) ON DELETE SET NULL,
    CONSTRAINT "FK_GRUPO_INSTRUCTOR" FOREIGN KEY ("PERF_ID") REFERENCES "TBL_INSTRUCTOR" ("PERF_ID"),
	--PARA LA CLAVE PRIMARIA LOS PRIMEROS 2 CAMPOS CORRESPONDEN A LA CLAVE FORANEA PARA CURSO.
	--EL CUARTO CAMPO ES EL AÑO: PERMITE IDENTIFICAR LOS GRUPOS DE UN CURSO POR AÑO, PUES PUEDEN HABER VARIOS GRUPOS DE UN CURSO A TRAVEZ DEL TIEMPO.
	--EL QUINTO ITERABLE: PERMITE IDENTIFICAR LOS CURSOS EN UN AÑO, PUEDES PUEDEN HABER VARIOS GRUPOS DE UN CURSO EN 1 AÑO.
	CONSTRAINT PK_TBL_GRUPO PRIMARY KEY(CAT_TITULO, CUR_NOMBRE, GRP_ANIO, GRP_ITERABLE)
   );   

--CREATE CLASE
CREATE TABLE TBL_CLASE 
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	CLS_CODIGO NUMBER(*,0) NOT NULL,
	PERF_ID VARCHAR2(50 BYTE) NOT NULL,
	CLS_FECHA DATE NOT NULL, --SE DEBE REGISTRAR FECHA HORAS MINUTOS Y SEGUNDOS
	CLS_DURACION_HORAS INTEGER NOT NULL, --REGISTAR SOLAMENTE LAS HORAS MINUTOS.
	CLS_DURACION_MINUTOS INTEGER NOT NULL,
	CLS_OBSERVACION VARCHAR2(1000 BYTE),
	--CAMPOS PARA LA CLAVE FORANEA DE GRUPO
	GRP_ANIO NUMBER(*,0) NOT NULL, 
	GRP_ITERABLE NUMBER(*,0) NOT NULL, 
	CUR_NOMBRE VARCHAR2(100 BYTE) NOT NULL, 
	CAT_TITULO VARCHAR2(100 BYTE) NOT NULL,
	CONSTRAINT FK_CLASE_INSTRUCTOR FOREIGN KEY(PERF_ID) REFERENCES TBL_INSTRUCTOR(PERF_ID) ON DELETE SET NULL,
	CONSTRAINT FK_CLASE_GRUPO FOREIGN KEY(GRP_ANIO, GRP_ITERABLE, CUR_NOMBRE, CAT_TITULO) REFERENCES TBL_GRUPO(GRP_ANIO, GRP_ITERABLE, CUR_NOMBRE, CAT_TITULO) ON DELETE SET NULL,
	CONSTRAINT PK_TBL_CLASE PRIMARY KEY(CLS_CODIGO) --CREO QUE ES NECESARIO CREAR OTRA SECUECIA PARA ESTA CLAVE
   );
   COMMENT ON COLUMN TBL_CLASE.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

--CREATE ALUMNO

  CREATE TABLE TBL_ALUMNO --LA RELACION CON EL PROGRAMA LA ESTABLECE UNA TABLA INTERMEDIA
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	PERF_ID VARCHAR2(50 BYTE) NOT NULL, 
	ALM_CODIGO VARCHAR2(20 BYTE), --EL CODIGO PUEDE SER NULABLE POR QUE ADMINISTRATIVOS Y DOCENTES NO SE MANEJAN DE LA MISMA FORMA, PUEDEN NO TENER CODIGOO 
	ALM_TIPO VARCHAR2(20 BYTE) NOT NULL,
	ALM_ESTADO NUMBER, --0 INACTIVO, 1 ACTIVO, SEGUN SU AFILIACION EN LA UNIVERSIDAD
	CONSTRAINT CKC_ALM_TIPO_ALUM CHECK (ALM_TIPO IN('Estudiante','Administrativo','Docente')),
	CONSTRAINT FK_ALUMNO_PERFIL FOREIGN KEY(PERF_ID) REFERENCES TBL_PERFIL(PERF_ID) ON DELETE SET NULL,
	CONSTRAINT PERF_ID PRIMARY KEY(PERF_ID)
	);
	COMMENT ON COLUMN TBL_ALUMNO.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

--CREATE FACULTAD
CREATE TABLE TBL_FACULTAD
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
   FAC_NOMBRE VARCHAR2(200 BYTE),
   CONSTRAINT PK_TBL_FACULTAD PRIMARY KEY(FAC_NOMBRE)
   );
   COMMENT ON COLUMN TBL_FACULTAD.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

--CREATE PROGRAMA 
CREATE TABLE TBL_PROGRAMA 
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	PRG_NOMBRE VARCHAR2(200 BYTE) NOT NULL, 
	FAC_NOMBRE VARCHAR2(200 BYTE),
	CONSTRAINT PK_TBL_PROGRAMA PRIMARY KEY(PRG_NOMBRE),
	CONSTRAINT FK_PROGRAMA_FACULTAD FOREIGN KEY(FAC_NOMBRE) REFERENCES TBL_FACULTAD(FAC_NOMBRE) ON DELETE SET NULL
   );
   COMMENT ON COLUMN TBL_PROGRAMA.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';
  
--TABLA INTERMEDIA PARA GESTIONAR RELACION DE MUCHOS A MUCHOS ENTRE ALUMNO Y PROGRAMA
--CREATE TBL_INTERMEDIA_ALUMNO_PROGRAMA
CREATE TABLE TBL_INTERMEDIA_ALUMNO_PROGRAMA
	(
	META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	PERF_ID VARCHAR2(50 BYTE) NOT NULL, --IDENTIFICADOR ALUNMNO
	PRG_NOMBRE VARCHAR2(200 BYTE) NOT NULL, --IDENTIFICADOR PROGRAMA
	CONSTRAINT PK_INTERMEDIA_ALUMNO_PROGRAMA PRIMARY KEY(PERF_ID, PRG_NOMBRE),
	CONSTRAINT FK_INTERMEDIA_PROGRAMA FOREIGN KEY(PRG_NOMBRE) REFERENCES TBL_PROGRAMA(PRG_NOMBRE) ON DELETE SET NULL,
	CONSTRAINT FK_INTERMEDIA_ALUMNO FOREIGN KEY(PERF_ID) REFERENCES TBL_ALUMNO(PERF_ID) ON DELETE SET NULL
	);
	COMMENT ON COLUMN TBL_INTERMEDIA_ALUMNO_PROGRAMA.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

--CREATE ASISTENCIA

  CREATE TABLE TBL_ASISTENCIA 
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	PERF_ID VARCHAR2(50 BYTE) NOT NULL, --IDENTIFICACION DEL ESTUDIANTE
	CLS_CODIGO NUMBER(*,0) NOT NULL, --CODIGO
	CONSTRAINT FK_ASISTENCIA_CLASE FOREIGN KEY(CLS_CODIGO) REFERENCES TBL_CLASE ON DELETE SET NULL,
	CONSTRAINT FK_ASISTENCIA_ALUMNO FOREIGN KEY(PERF_ID) REFERENCES TBL_ALUMNO ON DELETE SET NULL,
	CONSTRAINT PK_TBL_ASISTENCIA PRIMARY KEY(PERF_ID,CLS_CODIGO)
   );
   COMMENT ON COLUMN TBL_ASISTENCIA.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

   
--CREATE HORARIO

  CREATE TABLE TBL_HORARIO 
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	HR_ID NUMBER(*,0) NOT NULL,
	CAT_TITULO VARCHAR2(100 BYTE) NOT NULL, --PRIMARY DE GRUPO, SE USA EN FORANEA
	CUR_NOMBRE VARCHAR2(100 BYTE) NOT NULL, ---PRIMARY DE GRUPO, SE USA EN FORANEA
	GRP_ANIO NUMBER(*,0) NOT NULL, --PRIMARY DE GRUPO, SE USA EN FORANEA
	GRP_ITERABLE NUMBER(*,0) NOT NULL, --PRIMARY DE GRUPO, SE USA EN FORANEA
	HR_DIA VARCHAR2(50 BYTE) NOT NULL, 
	HR_HORAINICIO VARCHAR2(8 BYTE) NOT NULL, 
	HR_HORAFIN VARCHAR2(8 BYTE) NOT NULL, 
	HR_ESCENARIO VARCHAR2(100 BYTE) NOT NULL,
	CONSTRAINT PK_TBL_HORARIO PRIMARY KEY(HR_ID),
	CONSTRAINT FK_HORARIO_GRUPO FOREIGN KEY(CAT_TITULO, CUR_NOMBRE, GRP_ANIO, GRP_ITERABLE) REFERENCES TBL_GRUPO(CAT_TITULO, CUR_NOMBRE, GRP_ANIO, GRP_ITERABLE) ON DELETE SET NULL
   );
   COMMENT ON COLUMN TBL_HORARIO.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';
   
--CREATE INSCRIPCION
--CREATE INSCRIPCION

CREATE TABLE TBL_INSCRIPCION
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	--FECHAS EN LAS QUE OCURRE LA INSCRIPCION
	INSCR_FECHAINSCRIPCION DATE NOT NULL, 
	INSCR_FECHADESVINCULACION DATE,
	
	--IDENTIFICADOR DEL GRUPO
	GRP_ANIO NUMBER(*,0) NOT NULL, 
	GRP_ITERABLE NUMBER(*,0) NOT NULL, 
	CUR_NOMBRE VARCHAR2(100 BYTE) NOT NULL,
	CAT_TITULO VARCHAR2(100 BYTE) NOT NULL,
	
	--IDENTIFICADOR DEL ALLUMNO
	PERF_ID VARCHAR2(50 BYTE) NOT NULL, 
	
	CONSTRAINT FK_INSCRIPCION_ALUMNO FOREIGN KEY(PERF_ID) REFERENCES TBL_ALUMNO(PERF_ID) ON DELETE SET NULL,
	CONSTRAINT FK_INSCRIPCION_GRUPO FOREIGN KEY(CAT_TITULO, CUR_NOMBRE, GRP_ANIO, GRP_ITERABLE) REFERENCES TBL_GRUPO(CAT_TITULO, CUR_NOMBRE, GRP_ANIO, GRP_ITERABLE) ON DELETE SET NULL,
	CONSTRAINT PK_TBL_INSCRIPCION PRIMARY KEY(PERF_ID,CAT_TITULO, CUR_NOMBRE, GRP_ANIO, GRP_ITERABLE)
   );
   COMMENT ON COLUMN TBL_INSCRIPCION.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';
   
   
--CREATE COORDINADOR

CREATE TABLE TBL_COORDINADOR 
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
	PERF_ID VARCHAR2(50 BYTE) NOT NULL, 
	CONSTRAINT PK_TBL_COORDINADOR PRIMARY KEY(PERF_ID)
   );
   COMMENT ON COLUMN TBL_COORDINADOR.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';
   
   
--CREATE BANDEJA ENTRADA

  CREATE TABLE TBL_BANDEJA_ENTRADA
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
   PERF_ID VARCHAR2(50 BYTE) NOT NULL,
   CONSTRAINT PK_TBL_BANDEJA_ENTRADA PRIMARY KEY(PERF_ID)
   );
   COMMENT ON COLUMN TBL_BANDEJA_ENTRADA.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';
   
--CREATE BANDEJA SALIDA
------------------------------------------------------

  CREATE TABLE TBL_BANDEJA_SALIDA 
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
   PERF_ID VARCHAR2(50 BYTE),
   CONSTRAINT PK_TBL_BANDEJA_SALIDA PRIMARY KEY(PERF_ID)
   );
   COMMENT ON COLUMN TBL_BANDEJA_SALIDA.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';
   
   
--CREATE NOTIFICACION
CREATE TABLE TBL_NOTIFICACION 
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
   NTF_IDENTIFICADOR NUMBER(*,0) NOT NULL, 
	PERF_ID VARCHAR2(50 BYTE) NOT NULL, 
	NTF_EMISOR VARCHAR2(50 BYTE) NOT NULL, 
	NTF_ASUNTO VARCHAR2(150 BYTE) NOT NULL, 
	NTF_DESCRIPCION VARCHAR2(1000 BYTE) NOT NULL, 
	NTF_FECHAENVIO DATE NOT NULL, 
	NTF_DESTINATARIOS VARCHAR2(1000 BYTE) NOT NULL,
	CONSTRAINT PK_TBL_NOTIFICACION PRIMARY KEY (NTF_IDENTIFICADOR, PERF_ID),
	CONSTRAINT FK_NOTIFICACION_BANDEJA_SALIDA FOREIGN KEY(PERF_ID) REFERENCES TBL_BANDEJA_SALIDA(PERF_ID) ON DELETE SET NULL
   );
   COMMENT ON COLUMN TBL_NOTIFICACION.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';
   
--CREATE ALERTA

CREATE TABLE TBL_ALERTA 
   (	
   META_ELIMINADO INT NOT NULL, --MARCA COMO ELIMINADO UN OBJETO SI ES 1, LO CONTRARIO SI ES 0; EVITA BORRAR DATOS CON DELETE
   GRP_ANIO NUMBER(*,0) NOT NULL, --PARTE DE CLAVE COMPUESTA
	GRP_ITERABLE NUMBER(*,0) NOT NULL, --PARTE DE CLAVE COMPUESTA
	CUR_NOMBRE VARCHAR2(100 BYTE) NOT NULL, --PARTE DE CLAVE COMPUESTA Y RELACION A CURSO
	CAT_TITULO VARCHAR2(100 BYTE) NOT NULL, 
	ALERT_ASUNTO VARCHAR2(100 BYTE) NOT NULL, 
	ALERT_DESCRIPCION VARCHAR2(1000 BYTE) NOT NULL,
	CONSTRAINT FK_ALERTA_CURSO FOREIGN KEY (GRP_ANIO, GRP_ITERABLE, CUR_NOMBRE, CAT_TITULO) REFERENCES TBL_GRUPO(GRP_ANIO, GRP_ITERABLE, CUR_NOMBRE, CAT_TITULO) ON DELETE SET NULL,
	CONSTRAINT PK_TBL_ALERTA PRIMARY KEY (GRP_ANIO, GRP_ITERABLE, CUR_NOMBRE, CAT_TITULO)
   );
   COMMENT ON COLUMN TBL_ALERTA.META_ELIMINADO IS '1 SI EL REGISTRO SE HA ELIMINADO 0 DE LO CONTRARIO';

REM INSERTING into TBL_PERFIL
SET DEFINE OFF;
Insert into TBL_PERFIL (META_ELIMINADO,PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_IMAGEN,PERF_TIPOID,PERF_SEXO) values ('0','3','SMERT EMJ','edynsonjm@gmail.com',null,'CC','M');
Insert into TBL_PERFIL (META_ELIMINADO,PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_IMAGEN,PERF_TIPOID,PERF_SEXO) values ('0','1','EDYNSON MUnOZ JIMENEZ','edinsonmjim@unicauca.edu.co',null,'CC','M');
Insert into TBL_PERFIL (META_ELIMINADO,PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_IMAGEN,PERF_TIPOID,PERF_SEXO) values ('0','2','edynson muñoz jimenez','edynsonmj@gmail.com',null,'CC','M');
Insert into TBL_PERFIL (META_ELIMINADO,PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_IMAGEN,PERF_TIPOID,PERF_SEXO) values ('0','1141315391','MIGUEL ANGEL DORADO QUINAYAS','migueladorado@unicauca.edu.co',null,'CC','M');
Insert into TBL_PERFIL (META_ELIMINADO,PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_IMAGEN,PERF_TIPOID,PERF_SEXO) values ('0','1002958703','Yonathan Fernandez Guengue','tochavi@unicauca.edu.co',null,'CC','M');
Insert into TBL_PERFIL (META_ELIMINADO,PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_IMAGEN,PERF_TIPOID,PERF_SEXO) values ('0','1061786866','Luis Alexis Mendez Rojas','lamendez@unicauca.edu.co',null,'CC','M');
Insert into TBL_PERFIL (META_ELIMINADO,PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_IMAGEN,PERF_TIPOID,PERF_SEXO) values ('0','1061700114','Mitchelt Hernan Chilito Villota','mhchilito@unicauca.edu.co',null,'CC','M');
Insert into TBL_PERFIL (META_ELIMINADO,PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_IMAGEN,PERF_TIPOID,PERF_SEXO) values ('0','1061721857','JOHAN RICARDO MÉNDEZ CASTRO','johanmendez@unicauca.edu.co',null,'TI','M');
REM INSERTING into TBL_PROGRAMA
SET DEFINE OFF;
set define off;

   
Insert into TBL_ALUMNO (META_ELIMINADO,PERF_ID,ALM_CODIGO,ALM_TIPO,ALM_ESTADO) values ('0','3',null,'Estudiante',null);
Insert into TBL_ALUMNO (META_ELIMINADO,PERF_ID,ALM_CODIGO,ALM_TIPO,ALM_ESTADO) values ('0','1',null,'Administrativo',null);
Insert into TBL_ALUMNO (META_ELIMINADO,PERF_ID,ALM_CODIGO,ALM_TIPO,ALM_ESTADO) values ('0','2',null,'Docente',null);
Insert into TBL_ALUMNO (META_ELIMINADO,PERF_ID,ALM_CODIGO,ALM_TIPO,ALM_ESTADO) values ('0','1141315391',null,'Estudiante',null);
Insert into TBL_ALUMNO (META_ELIMINADO,PERF_ID,ALM_CODIGO,ALM_TIPO,ALM_ESTADO) values ('0','1002958703',null,'Estudiante',null);
Insert into TBL_ALUMNO (META_ELIMINADO,PERF_ID,ALM_CODIGO,ALM_TIPO,ALM_ESTADO) values ('0','1061786866',null,'Estudiante',null);
Insert into TBL_ALUMNO (META_ELIMINADO,PERF_ID,ALM_CODIGO,ALM_TIPO,ALM_ESTADO) values ('0','1061700114',null,'Estudiante',null);
Insert into TBL_ALUMNO (META_ELIMINADO,PERF_ID,ALM_CODIGO,ALM_TIPO,ALM_ESTADO) values ('0','1061721857',null,'Estudiante',null);


REM INSERTING into TBL_CATEGORIA_CURSO
SET DEFINE OFF;
Insert into TBL_CATEGORIA_CURSO (META_ELIMINADO,CAT_TITULO,CAT_DESCRIPCION,CAT_IMAGEN) values ('0','seleccionado ','Es un espacio para el entrenamiento y participación en eventos deportivos competitivos de carácter universitario, realizados a nivel local, nacional e internacional, bien sea en la red ASCUN o invitaciones de otras universidades.',null);
Insert into TBL_CATEGORIA_CURSO (META_ELIMINADO,CAT_TITULO,CAT_DESCRIPCION,CAT_IMAGEN) values ('0','Recreativo','El deporte recreativo es la modalidad definida como aquella practicada por placer y diversión, sin ninguna intención de competir o superar a un adversario.','176',null);
Insert into TBL_CATEGORIA_CURSO (META_ELIMINADO,CAT_TITULO,CAT_DESCRIPCION,CAT_IMAGEN) values ('0','Semillero','Este espacio tiene la facultad de ayudar a desarrollar destrezas físicas, hacer ejercicios, socializar, divertirse, aprender a jugar formando parte de un grupo o equipo, aprender a jugar limpio y a mejorar su autoestima.',null);
Insert into TBL_CATEGORIA_CURSO (META_ELIMINADO,CAT_TITULO,CAT_DESCRIPCION,CAT_IMAGEN) values ('1','prueba','Ririr8t',null);
Insert into TBL_CATEGORIA_CURSO (META_ELIMINADO,CAT_TITULO,CAT_DESCRIPCION,CAT_IMAGEN) values ('1','prurba2','Rur7r',null);
Insert into TBL_CATEGORIA_CURSO (META_ELIMINADO,CAT_TITULO,CAT_DESCRIPCION,CAT_IMAGEN) values ('1','ururt','Prueba',null);

REM INSERTING into TBL_CURSO
SET DEFINE OFF;
Insert into TBL_CURSO (META_ELIMINADO,CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('0','fútbol 1','Futbol','seleccionado ','Este curso es un programa copetitivo que busca desarrollar las habilidades tecnicas, tacticas y fisicas de los jugadores para enfrentar a otras facultades e instituciones a nivel local y nacional.',null);
Insert into TBL_CURSO (META_ELIMINADO,CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('0','baloncesto','Baloncesto','seleccionado ','Este curso es ideal para hombres y mujeres que buscan competir a nivel superior en baloncesto. Se enfoca en la práctica de técnicas avanzadas y la mejora de la condición física.',null);
Insert into TBL_CURSO (META_ELIMINADO,CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('0','natación ','Natacion','Semillero','Descr',null);
Insert into TBL_CURSO (META_ELIMINADO,CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('0','Baloncesto masculino','Baloncesto','Recreativo','El baloncesto recreativo es una modalidad del deporte del baloncesto que se enfoca en la diversión y el disfrute, más que en la competencia. En este entorno, los jugadores pueden desarrollar habilidades técnicas y tácticas, mientras que también se enfocan en la socialización y la relación con otros jugadores.',null);
Insert into TBL_CURSO (META_ELIMINADO,CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('0','baloncesto ','Baloncesto','seleccionado ','El curso de baloncesto seleccionado es un espacio dentro del programa de deporte competitivo de la Universidad del Cauca, diseñado para atletas con un alto nivel de habilidad y dedicación. En este entorno, los estudiantes seleccionados tienen la oportunidad de entrenar y competir en eventos deportivos universitarios de carácter local, nacional e internacional.',null);
Insert into TBL_CURSO (META_ELIMINADO,CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('0','ping pong','Ping pong','Recreativo','El ping pong recreativo es una modalidad del deporte del ping pong que se enfoca en la diversión y el disfrute, más que en la competencia. En este entorno, los jugadores pueden desarrollar habilidades técnicas y tácticas, mientras que también se enfocan en la socialización y la relación con otros jugadores.',null);

Insert into TBL_INSTRUCTOR (META_ELIMINADO,PERF_ID) values ('0','2');

REM INSERTING into TBL_COORDINADOR
SET DEFINE OFF;
Insert into TBL_COORDINADOR (META_ELIMINADO,PERF_ID) values ('0','1');
REM INSERTING into TBL_DEPORTE
SET DEFINE OFF;
Insert into TBL_DEPORTE (META_ELIMINADO,DEPT_NOMBRE) values ('0','Futbol');
Insert into TBL_DEPORTE (META_ELIMINADO,DEPT_NOMBRE) values ('0','Baloncesto');
Insert into TBL_DEPORTE (META_ELIMINADO,DEPT_NOMBRE) values ('0','Tenis');
Insert into TBL_DEPORTE (META_ELIMINADO,DEPT_NOMBRE) values ('0','Natacion');
Insert into TBL_DEPORTE (META_ELIMINADO,DEPT_NOMBRE) values ('0','Ping pong');
Insert into TBL_DEPORTE (META_ELIMINADO,DEPT_NOMBRE) values ('0','Voleibol');
Insert into TBL_DEPORTE (META_ELIMINADO,DEPT_NOMBRE) values ('0','Atletismo');
REM INSERTING into TBL_FACULTAD
SET DEFINE OFF;
Insert into TBL_FACULTAD (META_ELIMINADO,FAC_NOMBRE) values ('0','fiet');

REM INSERTING into TBL_ESCENARIO
SET DEFINE OFF;
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Piscina Olímpica','Natación. Sección de clavados fuera de servicio.',0,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Pista Atlética','Medidas reglamentarias.',1,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Cancha Descubierta de Voleibol','Medidas reglamentarias.',1,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Cancha Polifuncional Descubierta','Baloncesto, fútbol de salón, voleibol.',1,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Coliseo Cubierto Universitario','Baloncesto, fútbol de salón, fútbol sala, voleibol, actividades culturales.',3,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Patinódromo','Medidas reglamentarias.',0,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Dojos Cubiertos','Karate do, aikido, taekwondo.',0,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Sala de Ajedrez',NULL,0,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Salón de Aeróbicos y Baile Deportivo',NULL,0,1);
Insert into TBL_ESCENARIO (META_ELIMINADO,ESC_ID,ESC_NOMBRE,ESC_DESCRIPCION,ESC_NUM_TRIBUNAS,ESC_DISPONIBLE) values (0,SEQ_ESC_ID.NEXTVAL,'Sala de Ping Pong',NULL,0,1);