--------------------------------------------------------
-- Archivo creado  - lunes-octubre-07-2024   
--------------------------------------------------------
DROP TABLE "TEST"."NOTIFICACION_ENTRADA" cascade constraints;
DROP TABLE "TEST"."TBL_ALERTA" cascade constraints;
DROP TABLE "TEST"."TBL_ALUMNO" cascade constraints;
DROP TABLE "TEST"."TBL_ASISTENCIA" cascade constraints;
DROP TABLE "TEST"."TBL_BANDEJA_ENTRADA" cascade constraints;
DROP TABLE "TEST"."TBL_BANDEJA_SALIDA" cascade constraints;
DROP TABLE "TEST"."TBL_CATEGORIA_CURSO" cascade constraints;
DROP TABLE "TEST"."TBL_CLASE" cascade constraints;
DROP TABLE "TEST"."TBL_COORDINADOR" cascade constraints;
DROP TABLE "TEST"."TBL_CURSO" cascade constraints;
DROP TABLE "TEST"."TBL_DEPORTE" cascade constraints;
DROP TABLE "TEST"."TBL_FACULTAD" cascade constraints;
DROP TABLE "TEST"."TBL_GRUPO" cascade constraints;
DROP TABLE "TEST"."TBL_HORARIO" cascade constraints;
DROP TABLE "TEST"."TBL_IMAGEN" cascade constraints;
DROP TABLE "TEST"."TBL_INSCRIPCION" cascade constraints;
DROP TABLE "TEST"."TBL_INSTRUCTOR" cascade constraints;
DROP TABLE "TEST"."TBL_NOTIFICACION" cascade constraints;
DROP TABLE "TEST"."TBL_PERFIL" cascade constraints;
DROP TABLE "TEST"."TBL_PERTENECE" cascade constraints;
DROP TABLE "TEST"."TBL_PROGRAMA" cascade constraints;
DROP SEQUENCE "TEST"."SEQ_ID_IMAGEN";
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_IMAGEN
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."SEQ_ID_IMAGEN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table NOTIFICACION_ENTRADA
--------------------------------------------------------

  CREATE TABLE "TEST"."NOTIFICACION_ENTRADA" 
   (	"PERF_ID" VARCHAR2(50 BYTE), 
	"NTF_IDENTIFICADOR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_ALERTA
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_ALERTA" 
   (	"GRP_NOMBRE" VARCHAR2(100 BYTE), 
	"GRP_ANIO" NUMBER(*,0), 
	"GRP_ITERABLE" NUMBER(*,0), 
	"ALERT_ASUNTO" VARCHAR2(100 BYTE), 
	"ALERT_DESCRIPCION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_ALUMNO
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_ALUMNO" 
   (	"PERF_ID" VARCHAR2(50 BYTE), 
	"ALM_CODIGO" VARCHAR2(20 BYTE), 
	"FAC_NOMBRE" VARCHAR2(200 BYTE), 
	"ALM_TIPO" VARCHAR2(20 BYTE),
	"ALM_ESTADO" BOOLEAN
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_ASISTENCIA
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_ASISTENCIA" 
   (	"PERF_ID" VARCHAR2(50 BYTE), 
	"CLS_CODIGO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_BANDEJA_ENTRADA
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_BANDEJA_ENTRADA" 
   (	"PERF_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_BANDEJA_SALIDA
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_BANDEJA_SALIDA" 
   (	"PERF_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_CATEGORIA_CURSO
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_CATEGORIA_CURSO" 
   (	"CAT_TITULO" VARCHAR2(100 BYTE), 
	"CAT_DESCRIPCION" VARCHAR2(1000 BYTE),
	"CAT_URL_IMAGEN" VARCHAR2(1000 BYTE),
	"CAT_IMAGEN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";
 /*LOB ("CAT_IMAGEN") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;*/
--------------------------------------------------------
--  DDL for Table TBL_CLASE
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_CLASE" 
   (	"CLS_CODIGO" NUMBER(*,0), 
	"PERF_ID" VARCHAR2(50 BYTE), 
	"CLS_FECHA" DATE, 
	"CLS_HORA_INICIO" TIMESTAMP (6), 
	"CLS_HORA_FIN" TIMESTAMP (6), 
	"CLS_OBSERVACION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_COORDINADOR
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_COORDINADOR" 
   (	"PERF_ID" VARCHAR2(50 BYTE), 
	"COR_CODIGO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_CURSO
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_CURSO" 
   (	"CUR_NOMBRE" VARCHAR2(100 BYTE), 
	"DEPT_NOMBRE" VARCHAR2(100 BYTE), 
	"CAT_TITULO" VARCHAR2(100 BYTE), 
	"CUR_DESCRIPCION" VARCHAR2(1000 BYTE), 
	"CUR_IMAGEN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_DEPORTE
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_DEPORTE" 
   (	"DEPT_NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_FACULTAD
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_FACULTAD" 
   (	"FAC_NOMBRE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_GRUPO
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_GRUPO" 
   (	"GRP_NOMBRE" VARCHAR2(100 BYTE), 
	"GRP_ANIO" NUMBER(*,0), 
	"GRP_ITERABLE" NUMBER(*,0), 
	"CUR_NOMBRE" VARCHAR2(100 BYTE), 
	"GRP_IMAGEN" NUMBER(*,0), 
	"GRP_CUPOS" NUMBER(*,0), 
	"GRP_ESTADO" VARCHAR2(1 BYTE), 
	"GRP_FECHACREACION" DATE, 
	"GRP_FECHA_FINALIZACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 /*LOB ("GRP_IMAGEN") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;*/
--------------------------------------------------------
--  DDL for Table TBL_HORARIO
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_HORARIO" 
   (	"HR_ID" NUMBER(*,0), 
	"GRP_NOMBRE" VARCHAR2(100 BYTE), 
	"GRP_ANIO" NUMBER(*,0), 
	"GRP_ITERABLE" NUMBER(*,0), 
	"HR_DIA" VARCHAR2(50 BYTE), 
	"HR_HORAINICIO" VARCHAR2(8 BYTE), 
	"HR_HORAFIN" VARCHAR2(8 BYTE), 
	"HR_ESCENARIO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_IMAGEN
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_IMAGEN" 
   (	"IMG_ID" NUMBER(*,0), 
	"IMG_NOMBRE" VARCHAR2(200 BYTE), 
	"IMG_TIPO_ARCHIVO" VARCHAR2(100 BYTE), 
	"IMG_LONGITUD" NUMBER(*,0), 
	"IMG_DATOS" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMG_DATOS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TBL_INSCRIPCION
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_INSCRIPCION" 
   (	"INSCR_FECHAINSCRIPCION" TIMESTAMP (6), 
	"GRP_NOMBRE" VARCHAR2(100 BYTE), 
	"GRP_ANIO" NUMBER(*,0), 
	"GRP_ITERABLE" NUMBER(*,0), 
	"PERF_ID" VARCHAR2(50 BYTE), 
	"INSCR_FECHADESVINCULACION" DATE, 
	"FECHA_DESVINCULACION" TIMESTAMP (6),
	"INSCR_ESTADO" BOOLEAN 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_INSTRUCTOR
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_INSTRUCTOR" 
   (	"PERF_ID" VARCHAR2(50 BYTE), 
	"INST_CODIGO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_NOTIFICACION
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_NOTIFICACION" 
   (	"NTF_IDENTIFICADOR" NUMBER(*,0), 
	"PERF_ID" VARCHAR2(50 BYTE), 
	"NTF_EMISOR" VARCHAR2(50 BYTE), 
	"NTF_ASUNTO" VARCHAR2(150 BYTE), 
	"NTF_DESCRIPCION" VARCHAR2(1000 BYTE), 
	"NTF_FECHAENVIO" DATE, 
	"NTF_DESTINATARIOS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_PERFIL
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_PERFIL" 
   (	"PERF_ID" VARCHAR2(50 BYTE), 
	"PERF_NOMBRE" VARCHAR2(100 BYTE), 
	"PERF_CORREO" VARCHAR2(100 BYTE), 
	"PERF_IMAGEN" NUMBER(*,0), 
	"PERF_TIPOID" VARCHAR2(50 BYTE), 
	"PERF_SEXO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 /*LOB ("PERF_IMAGEN") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;*/
--------------------------------------------------------
--  DDL for Table TBL_PERTENECE
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_PERTENECE" 
   (	"PRG_NOMBRE" VARCHAR2(200 BYTE), 
	"PERF_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_PROGRAMA
--------------------------------------------------------

  CREATE TABLE "TEST"."TBL_PROGRAMA" 
   (	"PRG_NOMBRE" VARCHAR2(200 BYTE), 
	"FAC_NOMBRE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TEST.NOTIFICACION_ENTRADA
SET DEFINE OFF;
REM INSERTING into TEST.TBL_ALERTA
SET DEFINE OFF;
Insert into TEST.TBL_ALERTA (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,ALERT_ASUNTO,ALERT_DESCRIPCION) values ('Grupo A','2024','1','Este es el asunto del alerta gupo A','Descripcion de alerta');
Insert into TEST.TBL_ALERTA (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,ALERT_ASUNTO,ALERT_DESCRIPCION) values ('Grupo A','2024','2','Este es el asunto del alerta gupo A','Descripcion de alerta');
Insert into TEST.TBL_ALERTA (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,ALERT_ASUNTO,ALERT_DESCRIPCION) values ('Grupo A','2024','3','Este es el asunto del alerta gupo A','Descripcion de alerta');
Insert into TEST.TBL_ALERTA (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,ALERT_ASUNTO,ALERT_DESCRIPCION) values ('Grupo B','2024','4','Este es el asunto del alerta gupo C','Descripcion de alerta');
Insert into TEST.TBL_ALERTA (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,ALERT_ASUNTO,ALERT_DESCRIPCION) values ('Grupo A','2024','5','Este es el asunto del alerta gupo C','Descripcion de alerta');
Insert into TEST.TBL_ALERTA (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,ALERT_ASUNTO,ALERT_DESCRIPCION) values ('Grupo B','2024','6','Este es el asunto del alerta gupo C','Descripcion de alerta');
REM INSERTING into TEST.TBL_ALUMNO
SET DEFINE OFF;
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418643','101717011512','Facultad de ingenierias','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418646','101717011516','Facultad de ingenierias','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418647','101717011517','Facultad de ingenierias','Administrativo');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418648','101717011518','Facultad de contables','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418649','101717011519','Facultad de contables','Administrativo');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418650','101717011520','Facultad de contables','Docente');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418651','101717011521','Facultad de educacion','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418652','101717011522','Facultad de educacion','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418653','101717011523','Facultad de humanidades','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418654','101717011524','Facultad de humanidades','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418655','101717011525','Facultad de artes','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418656','101717011526','Facultad de artes','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418657','101717011527','Facultad de derecho','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418658','101717011528','Facultad de derecho','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418659','101717011529','Facultad de las guacas','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418660','101717011530','Facultad de las guacas','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418661','101717011531','Facultad de salud','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418662','101717011532','Facultad de salud','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418663','101717011533','Facultad de salud','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418664','101717011534','Facultad de las guacas','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418665','101717011535','Facultad de derecho','Estudiante');
Insert into TEST.TBL_ALUMNO (PERF_ID,ALM_CODIGO,FAC_NOMBRE,ALM_TIPO) values ('1004418666','101717011536','Facultad de artes','Estudiante');
REM INSERTING into TEST.TBL_ASISTENCIA
SET DEFINE OFF;
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418643','123');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418646','123');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418648','123');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418651','123');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418652','123');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418653','124');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418654','124');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418655','124');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418656','124');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418657','124');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418658','125');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418659','125');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418660','125');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418661','125');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418662','125');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418663','123');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418664','124');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418665','125');
Insert into TEST.TBL_ASISTENCIA (PERF_ID,CLS_CODIGO) values ('1004418666','125');
REM INSERTING into TEST.TBL_BANDEJA_ENTRADA
SET DEFINE OFF;
REM INSERTING into TEST.TBL_BANDEJA_SALIDA
SET DEFINE OFF;
REM INSERTING into TEST.TBL_CATEGORIA_CURSO
SET DEFINE OFF;
Insert into TEST.TBL_CATEGORIA_CURSO (CAT_TITULO,CAT_DESCRIPCION, CAT_URL_IMAGEN, CAT_IMAGEN) values ('Deporte semillero','Esta es la descripcion de la categoria Deporte semillero',null,null);
Insert into TEST.TBL_CATEGORIA_CURSO (CAT_TITULO,CAT_DESCRIPCION, CAT_URL_IMAGEN, CAT_IMAGEN) values ('Deporte seleccionados','Esta es la descripcion de la categoria Deporte seleccionados',null,null);
Insert into TEST.TBL_CATEGORIA_CURSO (CAT_TITULO,CAT_DESCRIPCION, CAT_URL_IMAGEN, CAT_IMAGEN) values ('Deporte recreativo','Esta es la descripcion de la categoria Deporte recreativo',null,null);
REM INSERTING into TEST.TBL_CLASE
SET DEFINE OFF;
Insert into TEST.TBL_CLASE (CLS_CODIGO,PERF_ID,CLS_FECHA,CLS_HORA_INICIO,CLS_HORA_FIN,CLS_OBSERVACION) values ('123','1004418641',to_date('15/04/24','DD/MM/RR'),to_timestamp('15/04/24 09:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('15/04/24 09:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null);
Insert into TEST.TBL_CLASE (CLS_CODIGO,PERF_ID,CLS_FECHA,CLS_HORA_INICIO,CLS_HORA_FIN,CLS_OBSERVACION) values ('124','1004418644',to_date('15/04/24','DD/MM/RR'),to_timestamp('15/04/24 09:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('15/04/24 09:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null);
Insert into TEST.TBL_CLASE (CLS_CODIGO,PERF_ID,CLS_FECHA,CLS_HORA_INICIO,CLS_HORA_FIN,CLS_OBSERVACION) values ('125','1004418645',to_date('15/04/24','DD/MM/RR'),to_timestamp('15/04/24 09:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('15/04/24 09:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null);
REM INSERTING into TEST.TBL_COORDINADOR
SET DEFINE OFF;
Insert into TEST.TBL_COORDINADOR (PERF_ID,COR_CODIGO) values ('1004418642','101717011511');
REM INSERTING into TEST.TBL_CURSO
SET DEFINE OFF;
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Futbol 11 femenino seleccionado','Futbol 11','Deporte seleccionados','Esta es una descripcion del curso deportivo','40');
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Futbol 11 masculino recreativo','Futbol 11','Deporte recreativo','Esta es una descripcion del curso deportivo','41');
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Futbol 11 masculino semillero','Futbol 11','Deporte semillero','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Sala femenino semillero','Futbol sala','Deporte semillero','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Sala femenino recreativo','Futbol sala','Deporte recreativo','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Sala femenino seleccionado','Futbol sala','Deporte seleccionados','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('sala masculino semilero','Futbol sala','Deporte semillero','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('sala masculino recreativo','Futbol sala','Deporte recreativo','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('sala masculino seleccionado','Futbol sala','Deporte seleccionados','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Voleibol femenino seleccionado','Voleibol','Deporte seleccionados','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Voleibol femenino semillero','Voleibol','Deporte semillero','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Basquetbol masculino semillero','Basquetbol','Deporte semillero','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Basquetbol masculino seleccionado','Basquetbol','Deporte seleccionados','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Voleibol masculino semillero','Voleibol','Deporte semillero','Esta es una descripcion del curso deportivo',null);
Insert into TEST.TBL_CURSO (CUR_NOMBRE,DEPT_NOMBRE,CAT_TITULO,CUR_DESCRIPCION,CUR_IMAGEN) values ('Basquetbol femenino seleccionado','Basquetbol','Deporte semillero','Esta es una descripcion del curso deportivo',null);
REM INSERTING into TEST.TBL_DEPORTE
SET DEFINE OFF;
Insert into TEST.TBL_DEPORTE (DEPT_NOMBRE) values ('Basquetbol');
Insert into TEST.TBL_DEPORTE (DEPT_NOMBRE) values ('Futbol 11');
Insert into TEST.TBL_DEPORTE (DEPT_NOMBRE) values ('Futbol sala');
Insert into TEST.TBL_DEPORTE (DEPT_NOMBRE) values ('Natacion');
Insert into TEST.TBL_DEPORTE (DEPT_NOMBRE) values ('Tennis');
Insert into TEST.TBL_DEPORTE (DEPT_NOMBRE) values ('Voleibol');
REM INSERTING into TEST.TBL_FACULTAD
SET DEFINE OFF;
Insert into TEST.TBL_FACULTAD (FAC_NOMBRE) values ('Facultad de artes');
Insert into TEST.TBL_FACULTAD (FAC_NOMBRE) values ('Facultad de contables');
Insert into TEST.TBL_FACULTAD (FAC_NOMBRE) values ('Facultad de derecho');
Insert into TEST.TBL_FACULTAD (FAC_NOMBRE) values ('Facultad de educacion');
Insert into TEST.TBL_FACULTAD (FAC_NOMBRE) values ('Facultad de humanidades');
Insert into TEST.TBL_FACULTAD (FAC_NOMBRE) values ('Facultad de ingenierias');
Insert into TEST.TBL_FACULTAD (FAC_NOMBRE) values ('Facultad de las guacas');
Insert into TEST.TBL_FACULTAD (FAC_NOMBRE) values ('Facultad de salud');
REM INSERTING into TEST.TBL_GRUPO
SET DEFINE OFF;
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','1','Futbol 11 femenino seleccionado','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','2','Futbol 11 masculino recreativo','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','3','Futbol 11 masculino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo B','2024','4','Futbol 11 masculino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','5','Sala femenino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo B','2024','6','Sala femenino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','7','Sala femenino seleccionado','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','8','sala masculino semilero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo B','2024','9','sala masculino semilero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','10','Sala femenino recreativo','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','11','sala masculino recreativo','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','12','sala masculino seleccionado','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','13','Voleibol femenino seleccionado','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','14','Voleibol femenino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo B','2024','15','Voleibol femenino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','16','Basquetbol masculino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo B','2024','17','Basquetbol masculino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','18','Basquetbol masculino seleccionado','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','19','Voleibol masculino semillero','30','1',to_date('10/05/23','DD/MM/RR'),null);
Insert into TEST.TBL_GRUPO (GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,CUR_NOMBRE,GRP_CUPOS,GRP_ESTADO,GRP_FECHACREACION,GRP_FECHA_FINALIZACION) values ('Grupo A','2024','20','Basquetbol femenino seleccionado','30','1',to_date('10/05/23','DD/MM/RR'),null);
REM INSERTING into TEST.TBL_HORARIO
SET DEFINE OFF;
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('1','Grupo A','2024','1','lunes','09:00','11:00','Cancha futbol');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('2','Grupo A','2024','2','lunes','02:00','04:00','Cancha futbol');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('3','Grupo A','2024','3','lunes','04:00','06:00','Cancha futbol');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('4','Grupo B','2024','4','lunes','06:00','08:00','Cancha futbol');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('5','Grupo A','2024','5','lunes','09:00','11:00','Coliseo');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('6','Grupo B','2024','6','lunes','11:00','01:00','Cancha 1');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('7','Grupo A','2024','7','lunes','02:00','04:00','Cancha 2');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('8','Grupo A','2024','8','lunes','04:00','06:00','Cancha 3');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('9','Grupo B','2024','9','lunes','06:00','08:00','Cancha 5');
Insert into TEST.TBL_HORARIO (HR_ID,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,HR_DIA,HR_HORAINICIO,HR_HORAFIN,HR_ESCENARIO) values ('10','Grupo A','2024','10','lunes','08:00','10:00','Cancha 2');
REM INSERTING into TEST.TBL_IMAGEN
SET DEFINE OFF;
Insert into TEST.TBL_IMAGEN (IMG_ID,IMG_NOMBRE,IMG_TIPO_ARCHIVO,IMG_LONGITUD) values ('40','firma2.png','image/png','409556');
Insert into TEST.TBL_IMAGEN (IMG_ID,IMG_NOMBRE,IMG_TIPO_ARCHIVO,IMG_LONGITUD) values ('41','20240727.jpg','image/jpeg','1958449');
Insert into TEST.TBL_IMAGEN (IMG_ID,IMG_NOMBRE,IMG_TIPO_ARCHIVO,IMG_LONGITUD) values ('43','20240727.jpg','image/jpeg','1958449');
Insert into TEST.TBL_IMAGEN (IMG_ID,IMG_NOMBRE,IMG_TIPO_ARCHIVO,IMG_LONGITUD) values ('44','firma2.png','image/png','409556');
REM INSERTING into TEST.TBL_INSCRIPCION
SET DEFINE OFF;
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','1','1004418643',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:00:01.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','1','1004418646',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:00:02.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','5','1004418648',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:01:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','5','1004418651',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:02:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','8','1004418652',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:02:01.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','8','1004418653',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:02:02.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','8','1004418654',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:02:03.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo B','2024','9','1004418655',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:03:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo B','2024','9','1004418656',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:04:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo B','2024','9','1004418657',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','10','1004418658',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:01.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','10','1004418659',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:02.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','10','1004418660',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:03.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','7','1004418661',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:04.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','7','1004418662',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:05.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo A','2024','7','1004418663',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:06.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo B','2024','6','1004418664',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:07.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo B','2024','6','1004418665',null,null);
Insert into TEST.TBL_INSCRIPCION (INSCR_FECHAINSCRIPCION,GRP_NOMBRE,GRP_ANIO,GRP_ITERABLE,PERF_ID,INSCR_FECHADESVINCULACION,FECHA_DESVINCULACION) values (to_timestamp('15/04/24 09:05:08.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'Grupo B','2024','6','1004418666',null,null);
REM INSERTING into TEST.TBL_INSTRUCTOR
SET DEFINE OFF;
Insert into TEST.TBL_INSTRUCTOR (PERF_ID,INST_CODIGO) values ('1004418641','101717011513');
Insert into TEST.TBL_INSTRUCTOR (PERF_ID,INST_CODIGO) values ('1004418644','101717011514');
Insert into TEST.TBL_INSTRUCTOR (PERF_ID,INST_CODIGO) values ('1004418645','101717011515');
REM INSERTING into TEST.TBL_NOTIFICACION
SET DEFINE OFF;
REM INSERTING into TEST.TBL_PERFIL
SET DEFINE OFF;
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418643','Camilo Anacona','camiload@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418642','Camilo Dorado H','camiload@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418641','Carolina','carola@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418644','Angela','Angela@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418645','Tania','Tania@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418646','Elmer','Elmer@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418647','Jose','Jose@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418648','Fabian','fabi@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418649','Kelvin','kelvin@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418650','Juliana','juli@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418651','Jineth','jineth@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418652','Emily','emi@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418653','Maria','mmaria@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418654','Leidy','leidys@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418655','Hector','hector@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418656','carlos','carlos@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418657','Alberto','Alberto@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418658','Dayana','Dayana@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418659','Marcela','Marcela@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418660','Nicolle','Nicolle@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418661','Karol','Karol@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418662','Vanessa','Vanessa@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418663','Julieth','Julieth@unicauca','CC','F');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418664','Stewart','Stewart@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418665','Javier','Javier@unicauca','CC','M');
Insert into TEST.TBL_PERFIL (PERF_ID,PERF_NOMBRE,PERF_CORREO,PERF_TIPOID,PERF_SEXO) values ('1004418666','Fernando','Fernando@unicauca','CC','M');
REM INSERTING into TEST.TBL_PERTENECE
SET DEFINE OFF;
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Administracion','1004418648');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Artes plasticas','1004418655');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Biologia','1004418652');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Ciencias politicas','1004418658');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Derecho','1004418657');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Derecho','1004418665');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Electronica','1004418646');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Filosofia','1004418654');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Fisioterapia','1004418661');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Ingenieria agroindustrial','1004418659');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Ingenieria agropecuaria','1004418660');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Ingenieria agropecuaria','1004418664');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Licenciatura en literatura','1004418653');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Matematicas','1004418651');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Medicina','1004418662');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Medicina','1004418663');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Musica','1004418656');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Musica','1004418666');
Insert into TEST.TBL_PERTENECE (PRG_NOMBRE,PERF_ID) values ('Sistemas','1004418643');
REM INSERTING into TEST.TBL_PROGRAMA
SET DEFINE OFF;
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Sistemas','Facultad de ingenierias');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Electronica','Facultad de ingenierias');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Ingenieria civil','Facultad de ingenierias');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Administracion','Facultad de contables');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Contaduria','Facultad de contables');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Matematicas','Facultad de educacion');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Biologia','Facultad de educacion');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Licenciatura en literatura','Facultad de humanidades');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Filosofia','Facultad de humanidades');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Artes plasticas','Facultad de artes');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Musica','Facultad de artes');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Derecho','Facultad de derecho');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Ciencias politicas','Facultad de derecho');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Ingenieria agroindustrial','Facultad de las guacas');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Ingenieria agropecuaria','Facultad de las guacas');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Fisioterapia','Facultad de salud');
Insert into TEST.TBL_PROGRAMA (PRG_NOMBRE,FAC_NOMBRE) values ('Medicina','Facultad de salud');
--------------------------------------------------------
--  DDL for Index ALUMNO_TO_INSCRIPCION_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."ALUMNO_TO_INSCRIPCION_FK" ON "TEST"."TBL_INSCRIPCION" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASOCIA_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."ASOCIA_FK" ON "TEST"."TBL_CURSO" ("DEPT_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CURSO_TO_GROUP_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."CURSO_TO_GROUP_FK" ON "TEST"."TBL_GRUPO" ("CUR_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTA_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."ESTA_FK" ON "TEST"."TBL_ALUMNO" ("FAC_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HORARIO_TO_GRUPO_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."HORARIO_TO_GRUPO_FK" ON "TEST"."TBL_HORARIO" ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMPARTE_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."IMPARTE_FK" ON "TEST"."TBL_CLASE" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INSCRIPCION_TO_GRUPO_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."INSCRIPCION_TO_GRUPO_FK" ON "TEST"."TBL_INSCRIPCION" ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTIFICACION_ENTRADA_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."NOTIFICACION_ENTRADA_FK" ON "TEST"."NOTIFICACION_ENTRADA" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTIFICACION_ENTRADA2_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."NOTIFICACION_ENTRADA2_FK" ON "TEST"."NOTIFICACION_ENTRADA" ("NTF_IDENTIFICADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTIFICACION_SALIDA_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."NOTIFICACION_SALIDA_FK" ON "TEST"."TBL_NOTIFICACION" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERTENECE_CATEGORIA_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."PERTENECE_CATEGORIA_FK" ON "TEST"."TBL_CURSO" ("CAT_TITULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERTENECE_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."PERTENECE_FK" ON "TEST"."TBL_PERTENECE" ("PRG_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERTENECE2_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."PERTENECE2_FK" ON "TEST"."TBL_PERTENECE" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_IMAGEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_IMAGEN" ON "TEST"."TBL_IMAGEN" ("IMG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NOTIFICACION_ENTRADA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_NOTIFICACION_ENTRADA" ON "TEST"."NOTIFICACION_ENTRADA" ("PERF_ID", "NTF_IDENTIFICADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_ALERTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_ALERTA" ON "TEST"."TBL_ALERTA" ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_ALUMNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_ALUMNO" ON "TEST"."TBL_ALUMNO" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_ASISTENCIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_ASISTENCIA" ON "TEST"."TBL_ASISTENCIA" ("PERF_ID", "CLS_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_BANDEJA_ENTRADA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_BANDEJA_ENTRADA" ON "TEST"."TBL_BANDEJA_ENTRADA" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_BANDEJA_SALIDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_BANDEJA_SALIDA" ON "TEST"."TBL_BANDEJA_SALIDA" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CATEGORIA_CURSO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_CATEGORIA_CURSO" ON "TEST"."TBL_CATEGORIA_CURSO" ("CAT_TITULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CLASE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_CLASE" ON "TEST"."TBL_CLASE" ("CLS_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_COORDINADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_COORDINADOR" ON "TEST"."TBL_COORDINADOR" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CURSO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_CURSO" ON "TEST"."TBL_CURSO" ("CUR_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_DEPORTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_DEPORTE" ON "TEST"."TBL_DEPORTE" ("DEPT_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_FACULTAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_FACULTAD" ON "TEST"."TBL_FACULTAD" ("FAC_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_GRUPO" ON "TEST"."TBL_GRUPO" ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_HORARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_HORARIO" ON "TEST"."TBL_HORARIO" ("HR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_INSCRIPCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_INSCRIPCION" ON "TEST"."TBL_INSCRIPCION" ("INSCR_FECHAINSCRIPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_INSTRUCTOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_INSTRUCTOR" ON "TEST"."TBL_INSTRUCTOR" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_NOTIFICACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_NOTIFICACION" ON "TEST"."TBL_NOTIFICACION" ("NTF_IDENTIFICADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PERFIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_PERFIL" ON "TEST"."TBL_PERFIL" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PERTENECE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_PERTENECE" ON "TEST"."TBL_PERTENECE" ("PRG_NOMBRE", "PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PROGRAMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PK_TBL_PROGRAMA" ON "TEST"."TBL_PROGRAMA" ("PRG_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECIBE_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."RECIBE_FK" ON "TEST"."TBL_ASISTENCIA" ("PERF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECIBE2_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."RECIBE2_FK" ON "TEST"."TBL_ASISTENCIA" ("CLS_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIENE_FK
--------------------------------------------------------

  CREATE INDEX "TEST"."TIENE_FK" ON "TEST"."TBL_PROGRAMA" ("FAC_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTIFICACION_ENTRADA
--------------------------------------------------------

  ALTER TABLE "TEST"."NOTIFICACION_ENTRADA" ADD CONSTRAINT "PK_NOTIFICACION_ENTRADA" PRIMARY KEY ("PERF_ID", "NTF_IDENTIFICADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."NOTIFICACION_ENTRADA" MODIFY ("NTF_IDENTIFICADOR" NOT NULL ENABLE);
  ALTER TABLE "TEST"."NOTIFICACION_ENTRADA" MODIFY ("PERF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ALERTA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_ALERTA" ADD CONSTRAINT "PK_TBL_ALERTA" PRIMARY KEY ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_ALERTA" MODIFY ("ALERT_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_ALERTA" MODIFY ("ALERT_ASUNTO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_ALERTA" MODIFY ("GRP_ITERABLE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_ALERTA" MODIFY ("GRP_ANIO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_ALERTA" MODIFY ("GRP_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ALUMNO
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_ALUMNO" ADD CONSTRAINT "PK_TBL_ALUMNO" PRIMARY KEY ("PERF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_ALUMNO" ADD CONSTRAINT "CKC_ALM_TIPO_TBL_ALUM" CHECK (ALM_TIPO in ('Estudiante','Administrativo','Docente')) ENABLE;
  ALTER TABLE "TEST"."TBL_ALUMNO" MODIFY ("ALM_TIPO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_ALUMNO" MODIFY ("FAC_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_ALUMNO" MODIFY ("ALM_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_ALUMNO" MODIFY ("PERF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ASISTENCIA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_ASISTENCIA" ADD CONSTRAINT "PK_TBL_ASISTENCIA" PRIMARY KEY ("PERF_ID", "CLS_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_ASISTENCIA" MODIFY ("CLS_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_ASISTENCIA" MODIFY ("PERF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_BANDEJA_ENTRADA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_BANDEJA_ENTRADA" ADD CONSTRAINT "PK_TBL_BANDEJA_ENTRADA" PRIMARY KEY ("PERF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_BANDEJA_ENTRADA" MODIFY ("PERF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_BANDEJA_SALIDA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_BANDEJA_SALIDA" ADD CONSTRAINT "PK_TBL_BANDEJA_SALIDA" PRIMARY KEY ("PERF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_BANDEJA_SALIDA" MODIFY ("PERF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CATEGORIA_CURSO
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_CATEGORIA_CURSO" ADD CONSTRAINT "PK_TBL_CATEGORIA_CURSO" PRIMARY KEY ("CAT_TITULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_CATEGORIA_CURSO" MODIFY ("CAT_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_CATEGORIA_CURSO" MODIFY ("CAT_TITULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CLASE
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_CLASE" ADD CONSTRAINT "PK_TBL_CLASE" PRIMARY KEY ("CLS_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_CLASE" MODIFY ("CLS_HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_CLASE" MODIFY ("CLS_FECHA" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_CLASE" MODIFY ("PERF_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_CLASE" MODIFY ("CLS_CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_COORDINADOR
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_COORDINADOR" ADD CONSTRAINT "PK_TBL_COORDINADOR" PRIMARY KEY ("PERF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_COORDINADOR" MODIFY ("COR_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_COORDINADOR" MODIFY ("PERF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CURSO
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_CURSO" ADD CONSTRAINT "PK_TBL_CURSO" PRIMARY KEY ("CUR_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_CURSO" MODIFY ("CUR_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_CURSO" MODIFY ("CAT_TITULO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_CURSO" MODIFY ("DEPT_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_CURSO" MODIFY ("CUR_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DEPORTE
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_DEPORTE" ADD CONSTRAINT "PK_TBL_DEPORTE" PRIMARY KEY ("DEPT_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_DEPORTE" MODIFY ("DEPT_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_FACULTAD
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_FACULTAD" ADD CONSTRAINT "PK_TBL_FACULTAD" PRIMARY KEY ("FAC_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_FACULTAD" MODIFY ("FAC_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_GRUPO
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_GRUPO" ADD CONSTRAINT "PK_TBL_GRUPO" PRIMARY KEY ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_GRUPO" MODIFY ("GRP_FECHACREACION" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_GRUPO" MODIFY ("CUR_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_GRUPO" MODIFY ("GRP_ITERABLE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_GRUPO" MODIFY ("GRP_ANIO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_GRUPO" MODIFY ("GRP_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_HORARIO
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_HORARIO" ADD CONSTRAINT "PK_TBL_HORARIO" PRIMARY KEY ("HR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_HORARIO" MODIFY ("HR_ESCENARIO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_HORARIO" MODIFY ("HR_HORAINICIO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_HORARIO" MODIFY ("HR_DIA" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_HORARIO" MODIFY ("GRP_ITERABLE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_HORARIO" MODIFY ("GRP_ANIO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_HORARIO" MODIFY ("GRP_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_HORARIO" MODIFY ("HR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_IMAGEN
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_IMAGEN" ADD CONSTRAINT "PK_IMAGEN" PRIMARY KEY ("IMG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_IMAGEN" MODIFY ("IMG_DATOS" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_IMAGEN" MODIFY ("IMG_TIPO_ARCHIVO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_IMAGEN" MODIFY ("IMG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_INSCRIPCION
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_INSCRIPCION" ADD CONSTRAINT "PK_TBL_INSCRIPCION" PRIMARY KEY ("INSCR_FECHAINSCRIPCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_INSCRIPCION" MODIFY ("PERF_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_INSCRIPCION" MODIFY ("GRP_ITERABLE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_INSCRIPCION" MODIFY ("GRP_ANIO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_INSCRIPCION" MODIFY ("GRP_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_INSCRIPCION" MODIFY ("INSCR_FECHAINSCRIPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_INSTRUCTOR" ADD CONSTRAINT "PK_TBL_INSTRUCTOR" PRIMARY KEY ("PERF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_INSTRUCTOR" MODIFY ("INST_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_INSTRUCTOR" MODIFY ("PERF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_NOTIFICACION
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_NOTIFICACION" ADD CONSTRAINT "PK_TBL_NOTIFICACION" PRIMARY KEY ("NTF_IDENTIFICADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_NOTIFICACION" MODIFY ("NTF_DESTINATARIOS" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_NOTIFICACION" MODIFY ("NTF_FECHAENVIO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_NOTIFICACION" MODIFY ("NTF_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_NOTIFICACION" MODIFY ("NTF_ASUNTO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_NOTIFICACION" MODIFY ("NTF_EMISOR" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_NOTIFICACION" MODIFY ("PERF_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_NOTIFICACION" MODIFY ("NTF_IDENTIFICADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PERFIL
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_PERFIL" ADD CONSTRAINT "PK_TBL_PERFIL" PRIMARY KEY ("PERF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_PERFIL" ADD CONSTRAINT "CKC_PERF_SEXO_TBL_PERF" CHECK (PERF_SEXO in ('M','F')) ENABLE;
  ALTER TABLE "TEST"."TBL_PERFIL" ADD CONSTRAINT "CKC_PERF_TIPOID_TBL_PERF" CHECK (PERF_TIPOID in ('CC','TI','CE','PP','PEP','DIE')) ENABLE;
  ALTER TABLE "TEST"."TBL_PERFIL" MODIFY ("PERF_SEXO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_PERFIL" MODIFY ("PERF_TIPOID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_PERFIL" MODIFY ("PERF_CORREO" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_PERFIL" MODIFY ("PERF_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_PERFIL" MODIFY ("PERF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PERTENECE
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_PERTENECE" ADD CONSTRAINT "PK_TBL_PERTENECE" PRIMARY KEY ("PRG_NOMBRE", "PERF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_PERTENECE" MODIFY ("PERF_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_PERTENECE" MODIFY ("PRG_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PROGRAMA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_PROGRAMA" ADD CONSTRAINT "PK_TBL_PROGRAMA" PRIMARY KEY ("PRG_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TBL_PROGRAMA" MODIFY ("FAC_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."TBL_PROGRAMA" MODIFY ("PRG_NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICACION_ENTRADA
--------------------------------------------------------

  ALTER TABLE "TEST"."NOTIFICACION_ENTRADA" ADD CONSTRAINT "FK_NOTIFICA_NOTIFICAC_TBL_BAND" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_BANDEJA_ENTRADA" ("PERF_ID") ENABLE;
  ALTER TABLE "TEST"."NOTIFICACION_ENTRADA" ADD CONSTRAINT "FK_NOTIFICA_NOTIFICAC_TBL_NOTI" FOREIGN KEY ("NTF_IDENTIFICADOR")
	  REFERENCES "TEST"."TBL_NOTIFICACION" ("NTF_IDENTIFICADOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_ALERTA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_ALERTA" ADD CONSTRAINT "FK_TBL_ALER_ALERTA_TO_TBL_GRUP" FOREIGN KEY ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE")
	  REFERENCES "TEST"."TBL_GRUPO" ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_ALUMNO
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_ALUMNO" ADD CONSTRAINT "FK_TBL_ALUM_ESTA_TBL_FACU" FOREIGN KEY ("FAC_NOMBRE")
	  REFERENCES "TEST"."TBL_FACULTAD" ("FAC_NOMBRE") ENABLE;
  ALTER TABLE "TEST"."TBL_ALUMNO" ADD CONSTRAINT "FK_TBL_ALUM_INHERITAN_TBL_PERF" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_PERFIL" ("PERF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_ASISTENCIA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_ASISTENCIA" ADD CONSTRAINT "FK_TBL_ASIS_RECIBE2_TBL_CLAS" FOREIGN KEY ("CLS_CODIGO")
	  REFERENCES "TEST"."TBL_CLASE" ("CLS_CODIGO") ENABLE;
  ALTER TABLE "TEST"."TBL_ASISTENCIA" ADD CONSTRAINT "FK_TBL_ASIS_RECIBE_TBL_ALUM" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_ALUMNO" ("PERF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_BANDEJA_ENTRADA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_BANDEJA_ENTRADA" ADD CONSTRAINT "FK_TBL_BAND_ENTRADA_T_TBL_PERF" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_PERFIL" ("PERF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_BANDEJA_SALIDA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_BANDEJA_SALIDA" ADD CONSTRAINT "FK_TBL_BAND_BANDEJA_S_TBL_PERF" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_PERFIL" ("PERF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CLASE
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_CLASE" ADD CONSTRAINT "FK_TBL_CLAS_IMPARTE_TBL_INST" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_INSTRUCTOR" ("PERF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_COORDINADOR
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_COORDINADOR" ADD CONSTRAINT "FK_TBL_COOR_INHERITAN_TBL_PERF" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_PERFIL" ("PERF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CURSO
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_CURSO" ADD CONSTRAINT "FK_CURSO_IMAGEN" FOREIGN KEY ("CUR_IMAGEN")
	  REFERENCES "TEST"."TBL_IMAGEN" ("IMG_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TEST"."TBL_CURSO" ADD CONSTRAINT "FK_TBL_CURS_ASOCIA_TBL_DEPO" FOREIGN KEY ("DEPT_NOMBRE")
	  REFERENCES "TEST"."TBL_DEPORTE" ("DEPT_NOMBRE") ENABLE;
  ALTER TABLE "TEST"."TBL_CURSO" ADD CONSTRAINT "FK_TBL_CURS_PERTENECE_TBL_CATE" FOREIGN KEY ("CAT_TITULO")
	  REFERENCES "TEST"."TBL_CATEGORIA_CURSO" ("CAT_TITULO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_GRUPO
--------------------------------------------------------
  ALTER TABLE "TEST"."TBL_GRUPO" ADD CONSTRAINT "FK_GRUPO_IMAGEN" FOREIGN KEY ("GRP_IMAGEN")
    REFERENCES "TEST"."TBL_IMAGEN" ("IMG_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TEST"."TBL_GRUPO" ADD CONSTRAINT "FK_TBL_GRUP_CURSO_TO__TBL_CURS" FOREIGN KEY ("CUR_NOMBRE")
	  REFERENCES "TEST"."TBL_CURSO" ("CUR_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_HORARIO
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_HORARIO" ADD CONSTRAINT "FK_TBL_HORA_HORARIO_T_TBL_GRUP" FOREIGN KEY ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE")
	  REFERENCES "TEST"."TBL_GRUPO" ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INSCRIPCION
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_INSCRIPCION" ADD CONSTRAINT "FK_TBL_INSC_ALUMNO_TO_TBL_ALUM" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_ALUMNO" ("PERF_ID") ENABLE;
  ALTER TABLE "TEST"."TBL_INSCRIPCION" ADD CONSTRAINT "FK_TBL_INSC_INSCRIPCI_TBL_GRUP" FOREIGN KEY ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE")
	  REFERENCES "TEST"."TBL_GRUPO" ("GRP_NOMBRE", "GRP_ANIO", "GRP_ITERABLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_INSTRUCTOR" ADD CONSTRAINT "FK_TBL_INST_INHERITAN_TBL_PERF" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_PERFIL" ("PERF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_NOTIFICACION
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_NOTIFICACION" ADD CONSTRAINT "FK_TBL_NOTI_NOTIFICAC_TBL_BAND" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_BANDEJA_SALIDA" ("PERF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PERTENECE
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_PERTENECE" ADD CONSTRAINT "FK_TBL_PERT_PERTENECE_TBL_ALUM" FOREIGN KEY ("PERF_ID")
	  REFERENCES "TEST"."TBL_ALUMNO" ("PERF_ID") ENABLE;
  ALTER TABLE "TEST"."TBL_PERTENECE" ADD CONSTRAINT "FK_TBL_PERT_PERTENECE_TBL_PROG" FOREIGN KEY ("PRG_NOMBRE")
	  REFERENCES "TEST"."TBL_PROGRAMA" ("PRG_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PROGRAMA
--------------------------------------------------------

  ALTER TABLE "TEST"."TBL_PROGRAMA" ADD CONSTRAINT "FK_TBL_PROG_TIENE_TBL_FACU" FOREIGN KEY ("FAC_NOMBRE")
	  REFERENCES "TEST"."TBL_FACULTAD" ("FAC_NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CATEGORIA
--------------------------------------------------------
  ALTER TABLE "TEST"."TBL_CATEGORIA_CURSO" ADD CONSTRAINT "FK_CATEGORIA_CURSO_IMAGEN" FOREIGN KEY ("CAT_IMAGEN")
    REFERENCES "TEST"."TBL_IMAGEN" ("IMG_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PERFIL
--------------------------------------------------------
  ALTER TABLE "TEST"."TBL_PERFIL" ADD CONSTRAINT "FK_PERFIL_IMAGEN" FOREIGN KEY ("PERF_IMAGEN")
    REFERENCES "TEST"."TBL_IMAGEN" ("IMG_ID") ON DELETE SET NULL ENABLE;
